// Auto-generated — DO NOT EDIT
export const audioMap = {
  "Welcome to MeasureQuest: Length Adventures! A Grade 3 Mathematics journey.": "/assets/audio/audio_welcome_to_measurequest_length_adventures_a_0.mp3",
  "Join Sam the Ruler as we explore centimetres, metres, and millimetres.": "/assets/audio/audio_join_sam_the_ruler_as_we_0.mp3",
  "Are you ready to master the language of length? Let us begin!": "/assets/audio/audio_are_you_ready_to_master_the_0.mp3",
  "Hmm, I wonder. Emma has a ribbon that is one metre and fifty centimetres long.": "/assets/audio/audio_hmm_i_wonder_emma_has_a_0.mp3",
  "She uses eighty-five centimetres of it. How much ribbon is left?": "/assets/audio/audio_she_uses_eightyfive_centimetres_of_it_0.mp3",
  "What if the two lengths are in different units? How do we solve that?": "/assets/audio/audio_what_if_the_two_lengths_are_0.mp3",
  "We might need to convert units first! Let us investigate together.": "/assets/audio/audio_we_might_need_to_convert_units_0.mp3",
  "Emma, Oliver, and Lily found a glowing treasure map in the old school library.": "/assets/audio/audio_emma_oliver_and_lily_found_a_0.mp3",
  "The map had a message: Only those who understand the language of length shall find the treasure.": "/assets/audio/audio_the_map_had_a_message_only_0.mp3",
  "Emma looked up and whispered — do you know how to measure things?": "/assets/audio/audio_emma_looked_up_and_whispered_do_0.mp3",
  "At the first station, Sam the Carpenter handed each child a ruler.": "/assets/audio/audio_at_the_first_station_sam_the_0.mp3",
  "Always start from zero! Ten small marks make one centimetre.": "/assets/audio/audio_always_start_from_zero_ten_small_0.mp3",
  "A hundred centimetres make one metre. They measured pencils, erasers, and planks.": "/assets/audio/audio_a_hundred_centimetres_make_one_metre_0.mp3",
  "The garden was enormous! Sunflowers taller than Oliver stood in rows.": "/assets/audio/audio_the_garden_was_enormous_sunflowers_taller_0.mp3",
  "Lena handed them a metre stick. This sunflower is two metres and thirty centimetres tall!": "/assets/audio/audio_lena_handed_them_a_metre_stick_0.mp3",
  "For long things, use metres. One metre equals one hundred centimetres.": "/assets/audio/audio_for_long_things_use_metres_one_0.mp3",
  "At the stadium, Emma jumped one hundred and forty-five centimetres.": "/assets/audio/audio_at_the_stadium_emma_jumped_one_0.mp3",
  "Noah jumped one metre and fifty-two centimetres. Who jumped further?": "/assets/audio/audio_noah_jumped_one_metre_and_fiftytwo_0.mp3",
  "Convert to the same unit first! One metre fifty-two centimetres equals one hundred and fifty-two centimetres. Noah won by seven centimetres!": "/assets/audio/audio_convert_to_the_same_unit_first_0.mp3",
  "Welcome to the Ruler Lab! Look carefully at each ruler.": "/assets/audio/audio_welcome_to_the_ruler_lab_look_0.mp3",
  "Always start measuring from zero. Count the big marks for centimetres and the small marks for millimetres.": "/assets/audio/audio_always_start_measuring_from_zero_count_0.mp3",
  "Ten millimetres make one centimetre. Read where the coloured bar ends on the ruler.": "/assets/audio/audio_ten_millimetres_make_one_centimetre_read_0.mp3",
  "Welcome to the Unit Converter station! Drag the sliders to see live conversions.": "/assets/audio/audio_welcome_to_the_unit_converter_station_0.mp3",
  "To convert metres to centimetres, multiply by one hundred. Three metres equals three hundred centimetres.": "/assets/audio/audio_to_convert_metres_to_centimetres_multiply_0.mp3",
  "Try the quick quiz at the bottom to test your understanding!": "/assets/audio/audio_try_the_quick_quiz_at_the_0.mp3",
  "Welcome to the Estimation Slider! Estimate the length of each object before revealing the answer.": "/assets/audio/audio_welcome_to_the_estimation_slider_estimate_0.mp3",
  "Use your body as a guide. Your finger is about one centimetre. Your hand span is about fifteen centimetres.": "/assets/audio/audio_use_your_body_as_a_guide_0.mp3",
  "The closer your estimate, the more stars you earn. Give it your best guess!": "/assets/audio/audio_the_closer_your_estimate_the_more_0.mp3",
  "Welcome to Spot the Error! Look at each measurement conversion carefully.": "/assets/audio/audio_welcome_to_spot_the_error_look_0.mp3",
  "Is the conversion correct or wrong? Think before you answer!": "/assets/audio/audio_is_the_conversion_correct_or_wrong_0.mp3",
  "Remember: to convert metres to centimetres, multiply by one hundred. Never just move a digit!": "/assets/audio/audio_remember_to_convert_metres_to_centimetres_0.mp3",
  "Congratulations! You have completed all four simulation stations!": "/assets/audio/audio_congratulations_you_have_completed_all_four_0.mp3",
  "You are now entering Test Mode — ten exciting worlds with ten questions each!": "/assets/audio/audio_you_are_now_entering_test_mode_0.mp3",
  "All the best on your measurement adventure. You have got this!": "/assets/audio/audio_all_the_best_on_your_measurement_0.mp3",
  "World One: Ruler Meadow. Practise reading rulers and choosing the right units. Good luck!": "/assets/audio/audio_world_one_ruler_meadow_practise_reading_0.mp3",
  "World Two: Conversion Canyon. Convert between centimetres and metres. Remember to multiply by one hundred!": "/assets/audio/audio_world_two_conversion_canyon_convert_between_0.mp3",
  "World Three: Estimation Island. How good are your estimation skills? Use your body benchmarks!": "/assets/audio/audio_world_three_estimation_island_how_good_0.mp3",
  "World Four: Metre Mountain. Work with mixed units — metres and centimetres together.": "/assets/audio/audio_world_four_metre_mountain_work_with_0.mp3",
  "World Five: Comparison Creek. Compare and order lengths. Convert to the same unit first!": "/assets/audio/audio_world_five_comparison_creek_compare_and_0.mp3",
  "World Six: Word Problem Woods. Solve one-step and two-step length word problems.": "/assets/audio/audio_world_six_word_problem_woods_solve_0.mp3",
  "World Seven: Conversion Castle. Advanced unit conversions both ways — you can do it!": "/assets/audio/audio_world_seven_conversion_castle_advanced_unit_0.mp3",
  "World Eight: Perimeter Plaza. Find the perimeter of shapes by adding all the sides.": "/assets/audio/audio_world_eight_perimeter_plaza_find_the_0.mp3",
  "World Nine: Mixed Mastery. A mix of all measurement topics. Show what you know!": "/assets/audio/audio_world_nine_mixed_mastery_a_mix_0.mp3",
  "World Ten: Length Legend Challenge. The ultimate test — one hundred questions worth of mastery. This is your moment!": "/assets/audio/audio_world_ten_length_legend_challenge_the_0.mp3",
  "Brilliant! That is correct!": "/assets/audio/audio_brilliant_that_is_correct_0.mp3",
  "Good try! Check the hint and try the next one.": "/assets/audio/audio_good_try_check_the_hint_and_0.mp3",
  "Congratulations! You have completed MeasureQuest: Length Adventures!": "/assets/audio/audio_congratulations_you_have_completed_measurequest_length_0.mp3",
  "Let us look at what you learned. Always start your ruler from zero, and read in millimetres and centimetres for small objects.": "/assets/audio/audio_let_us_look_at_what_you_0.mp3",
  "One metre equals one hundred centimetres. Use metres for longer lengths like rooms and roads.": "/assets/audio/audio_one_metre_equals_one_hundred_centimetres_0.mp3",
  "When you estimate, use your body as a guide — your finger, your hand, your arm.": "/assets/audio/audio_when_you_estimate_use_your_body_0.mp3",
  "To convert, multiply by one hundred from metres to centimetres, and divide by one hundred to go back.": "/assets/audio/audio_to_convert_multiply_by_one_hundred_0.mp3",
  "Before comparing lengths, make sure they are all in the same unit!": "/assets/audio/audio_before_comparing_lengths_make_sure_they_0.mp3",
  "And for word problems, always figure out what you are looking for first, then calculate step by step.": "/assets/audio/audio_and_for_word_problems_always_figure_0.mp3",
  "You are a true Length Legend! Well done!": "/assets/audio/audio_you_are_a_true_length_legend_0.mp3",
  "The treasure chest burst open — and inside were not gold coins, but something even better.": "/assets/audio/audio_the_treasure_chest_burst_open_and_0.mp3",
  "A certificate that read: Length Legend — awarded to the brave explorer who mastered the art of measurement!": "/assets/audio/audio_a_certificate_that_read_length_legend_0.mp3",
  "Emma, Oliver, and Lily cheered — and so did you. You are a true Length Legend!": "/assets/audio/audio_emma_oliver_and_lily_cheered_and_0.mp3"
};
